#Here is where you define services in terms of ports and command line
#programs, this is just an example to start you off of a very simple
#service that serves hello world on two ports, load balanced
#and with failover
services:
  -
    port: 9000
    #having a proxy port hooks up nginx
    proxy_port: 9090

    #files ending in the following space separated patterns
    reload_on_changes:
      - rb
    programs:
      -
        port: 9001
        exec: ./api/glgimpact.rb 9001
      -
        port: 9002
        exec: ./api/glgimpact.rb 9002